example:
  image: mrunal/awstats:7.6
#  build: .
  volumes:
    - ./mycron:/mycron
    - /var/log/mail.log:/var/log/mail.log
    - ./awstats.linoxide.conf:/usr/lib/cgi-bin/awstats/awstats.linoxide.conf
    - /logs/example.com/access.log:/root/example.com/access.log                       # Change dir name as domain name and access log name
    - ./awstats.example.com.conf:/usr/lib/cgi-bin/awstats/awstats.example.com.conf    # Change file name as domain name in conf
    - ./run.sh:/run.sh
  ports:
    - 8080:80
